### PR TITLE
Append Only Set: include view to get elements by index

### PR DESCRIPTION
**Pull request by bh2smith**
In some scenarios (cf. https://github.com/gnosis/dex-contracts/issues/269) it can be beneficial to expose a retrieval function for set element search based on order of inclusion (i.e. index). Since our set is iterable, it has a root element and thus, elements in this linked list have an index.

Now, any contract using such a library can expose a `public view`which might look as follows:

```py
    function accountIdToAddressMap(uint16 id) public view returns (address) {
        return allUsers.atIndex(id);
    }
```

**TestPlan:** `truffle test`

### CODE REVIEW

**Comment by fleupold** [comment]
Should this live here? 

https://github.com/gnosis/solidity-data-structures/blob/master/contracts/libraries/IterableAppendOnlySet.sol

Would probably be good to not have two copies of the same helper datastructure.

**Comment by bh2smith** [comment]
> Should this live here?

I don't understand your question... That is exactly where I made the changes.

**Comment by josojo** [comment]
@bh2smith Once you are back from vacation, could you please close or fix this PR?

**Comment by bh2smith** [comment]
> Once you are back from vacation, could you please close or fix this PR?

@josojo - Yes I will try and fix, but it seems to be a weird travis problem with JS. Not exactly sure how to deal with it.

**Pull request merged**
